Repository cloudbees/arcalos-jenkins-x-versions, pull requests merged in 2019-10, with the labels that each got.

#7 chore(deps): Update arcalos-boot-config to 1.0.3
  git/github.com/cloudbees/arcalos-boot-config.yml
Labels: approved, size/XS

#3 fix: attempting to fix CI
  ci.sh
  jenkins-x-arcalos.yml
  jenkins-x.yml
  jx/bdd/arcalos/ci.sh
Labels: approved, lgtm, size/L

#8 chore: building the actual PR
  ci.sh
  jenkins-x.yml
Labels: approved, lgtm, size/L

#9 fix: attempting to set the PR SHA
  ci.sh
  jx/bdd/arcalos/README.md
  jx/bdd/arcalos/ci.sh
  jx/bdd/arcalos/cluster.yaml
  jx/bdd/arcalos/jx-requirements.yml
  jx/bdd/arcalos/parameters.yaml
  jx/scripts/ci-github.sh
  jx/scripts/get-jx-prerelease-state.sh
  jx/scripts/release-jx.sh
  jx/scripts/release.sh
  jx/scripts/update-jx-bot.sh
  jx/scripts/update-jx-clients.sh
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/L

#15 feat: include test phase in ci build
  ci.sh
Labels: approved, lgtm, size/XS

#23 feat: update to boot-config 1.0.5
  git/github.com/cloudbees/arcalos-boot-config.yml
Labels: approved, size/XS

#25 chore(deps): bump arcalos-boot-config from 1.0.5 to 1.0.6
  git/github.com/cloudbees/arcalos-boot-config.yml
Labels: approved, size/XS

#26 chore(deps): bump arcalos-boot-config from 1.0.6 to 1.0.8
  git/github.com/cloudbees/arcalos-boot-config.yml
Labels: approved, size/XS, updatebot

#32 feat: added release and versions pr
  jenkins-x-arcalos.yml
  update-bot.sh
Labels: approved, lgtm, size/S

#34 fix: using builder-jx for the update-bot script execution
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/XS

#36 fix: builder image for release pipeline
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/XS

#37 fix: git env vars for update bot step
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/S

#38 fix: path to update arcalos config version stream release
  update-bot.sh
Labels: approved, lgtm, size/XS

#39 fix: correct update-bot file name
  update-bot.sh
Labels: approved, lgtm, size/XS

#40 fix: include v prefix in version tag for update bot
  update-bot.sh
Labels: approved, lgtm, size/XS

#60 feat: ensure bdd tests are run as part of CI
  ci.sh
Labels: size/XS

#65 feat: using staging certs
  jenkins-x-arcalos.yml
Labels: approved, size/XS

#61 feat: fail if there are any script failures
  ci.sh
Labels: approved

#67 feat: switch to use image with jxt installed
  jenkins-x-arcalos.yml
Labels: approved, size/XS

#74 chore(deps): bump versions
  charts/cloudbees/jx-tenant-service.yml
  charts/jenkins-x/environment-controller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/lighthouse.yml
  charts/jenkins-x/prow.yml
  charts/stable/nginx-ingress.yml
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs12x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-php5x.yml
  docker/gcr.io/jenkinsxio/builder-php7x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  git/github.com/cloudbees/arcalos-boot-config.yml
  jenkins-x-arcalos.yml
Labels: size/L, updatebot
