Repository cloudbees/arcalos-jenkins-x-versions, pull requests merged in 2020-02, with the labels that each got.

#288 chore: update variables for lighthouse
  jenkins-x-arcalos.yml
Labels: approved, size/M

#292 fix: call arcalos config in ci
  ci.sh
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/S

#295 chore: unused pipeline vars
  jenkins-x-arcalos.yml
Labels: size/S
